# lines
LINE_A = 'LINE_A'
LINE_B = 'LINE_B'

LINES = {
    LINE_A: 'A',
    LINE_B: 'B'
}

# channels
CHANNEL_PITCH = 'PITCH'
CHANNEL_YAW = 'YAW'
CHANNEL_ROLL = 'ROLL'

CHANNELS = {
    CHANNEL_PITCH: CHANNEL_PITCH,
    CHANNEL_YAW: CHANNEL_YAW,
    CHANNEL_ROLL: CHANNEL_ROLL,
}

# commands
GET_ANSWER = 'GET_ANSWER'
GET_DATA = 'GET_DATA'
SEND_DATA = 'SEND_DATA'
BLOCK = 'BLOCK'
RELEASE = 'RELEASE'
SWAP_LINE = 'SWAP_LINE'

COMMANDS = {
    GET_ANSWER: GET_ANSWER,
    GET_DATA: GET_DATA,
    SEND_DATA: SEND_DATA,
    BLOCK: BLOCK,
    RELEASE: RELEASE,
}

# endpoints states
IS_BUSY = 'IS_BUSY'
IS_GENERATING = 'IS_GENERATING'
IS_FROZEN = 'IS_FROZEN'
IS_FUNCTIONING = 'IS_FUNCTIONING'
IS_SERVICE_NEEDED = 'IS_SERVICE_NEEDED'

STATES = {
    IS_BUSY: IS_BUSY,
    IS_GENERATING: IS_GENERATING,
    IS_FROZEN: IS_FROZEN,
    IS_FUNCTIONING: IS_FUNCTIONING,
    IS_SERVICE_NEEDED: IS_SERVICE_NEEDED,
}

ANGLE = 'ANGLE'
ANGULAR_VELOCITY = 'ANGLE_VELOCITY'
ANGULAR_ACCELERATION = 'ANGULAR_ACCELERATION'

CHARACTERISTICS = {
    ANGLE: ANGLE,
    ANGULAR_VELOCITY: ANGULAR_VELOCITY,
    ANGULAR_ACCELERATION: ANGULAR_ACCELERATION,
}
